### PR TITLE
fix: install react-server-dom-webpack during init and deploy for App Router

### LINKED ISSUE #22: Vinext failes to work on new hello world Next.js app
## Version
```bash
$ node --version
v22.19.0
$ sw_vers
ProductName:            macOS
ProductVersion:         15.7.4
BuildVersion:           24G517
```

## Reproduction Steps

Bootstrap a new Next.js project:

```
$ npx create-next-app@latest my-app --yes
$ cd my-app
```

Install and initialize vinext:

```bash
$ npm install vinext
$ npx vinext init

  vinext init

  Running compatibility check...


  vinext compatibility report
  ========================================

  Imports: 1/2 fully supported
    ~  next/font/google (1 file) — fonts loaded from CDN, not self-hosted at build time
    ✓  next/image (1 file) — uses @unpic/react (no local optimization yet)

  Libraries: 1/1 compatible
    ✓  tailwindcss

  Project structure:
    ✓  App Router (app/)
    ✓  1 page(s)
    ✓  1 layout(s)

  ----------------------------------------
  Overall: 92% compatible (5 supported, 1 partial, 0 issues)

  Partial support (may need attention):
    ~  next/font/google — fonts loaded from CDN, not self-hosted at build time


  vinext init complete!

    - Skipped vite.config.ts (already exists, use --force to overwrite)

  Next steps:
    npm run dev:vinext    Start the vinext dev server
    npm run dev           Start Next.js (still works as before)
```

Run the dev server:

```bash
$ npm run dev:vinext

> my-app@0.1.0 dev:vinext
> vite dev --port 3001

Failed to resolve dependency: react-server-dom-webpack/server.edge, present in rsc 'optimizeDeps.include'
Failed to resolve dependency: react-server-dom-webpack/client.edge, present in rsc 'optimizeDeps.include'
Failed to resolve dependency: react-server-dom-webpack/client.edge, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: react-server-dom-webpack/client.browser, present in client 'optimizeDeps.include'

  VITE v7.3.1  ready in 331 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
[vite] connected.
1:17:33 PM [vite] Internal server error: Could not resolve "react-server-dom-webpack/server.edge" imported by "@vitejs/plugin-rsc". Is it installed?
      at eval (plugin-rsc:false:1:25)...
```

### PR DESCRIPTION
**Pull request by southpolesteve**
## Summary

Fixes #22 — `vinext init` on a fresh `create-next-app` project fails with `Could not resolve "react-server-dom-webpack/server.edge"`.

## Root Cause

Two compounding issues:

1. **Missing dependency**: `getInitDeps()` didn't include `react-server-dom-webpack` in the list of packages to install during `vinext init`. While vinext lists it as a direct dependency, Vite needs it resolvable from the **project root** `node_modules/`, not nested inside `vinext/node_modules/`.

2. **React version mismatch**: `react-server-dom-webpack@19.2.4` requires `react@^19.2.4` as a peer dep, but `create-next-app@latest` ships `react@19.2.3`. This version conflict causes npm to either nest rsdw (npm 7-9) or hard-fail with `ERESOLVE` (npm 11+).

## Fix

- Add `react-server-dom-webpack` to `getInitDeps()` for App Router projects
- Add `getReactUpgradeDeps()` that detects when the installed React is too old for rsdw
- Before installing dev deps, upgrade `react` and `react-dom` as **regular dependencies** (without `-D`) to maintain their position in `dependencies` rather than `devDependencies`
- Apply the same fix to `vinext deploy` for parity (per AGENTS.md guidance)
- Add a **CI smoke test** that scaffolds a real `create-next-app` project, runs `vinext init`, starts the dev server, and verifies HTTP 200

## Testing

- 1814 existing tests pass (0 failures)
- 12 new unit tests for `getReactUpgradeDeps`, rsdw dependency detection, and React upgrade ordering
- New `create-next-app` CI job validates the end-to-end flow
- Typecheck and lint clean

### CODE REVIEW

File: packages/vinext/src/init.ts [hunk 1]
```diff
@@ -136,14 +137,47 @@ export function isDepInstalled(root: string, dep: string): boolean {
...
+ * Check if react/react-dom need upgrading for react-server-dom-webpack compatibility.
+ *
+ * react-server-dom-webpack versions are pinned to match their React version
+ * (e.g. rsdw@19.2.4 requires react@^19.2.4). When a project has an older
+ * React (e.g. create-next-app ships react@19.2.3), we need to upgrade
+ * react/react-dom BEFORE installing rsdw to avoid peer-dep conflicts.
+ *
+ * Returns ["react@latest", "react-dom@latest"] if upgrade is needed, [] otherwise.
+ */
+export function getReactUpgradeDeps(root: string): string[] {
```
Comment (FredKSchott) [inline packages/vinext/src/init.ts:155]: See implementation in https://github.com/cloudflare/vinext/pull/18/changes -- you want to be careful with reading node_modules directly from disk, too unreliable at scale due to how common hoisting, symlinking, monorepo setups, etc. etc. can be. 

Much better to leverage Node's built-in `require` implementation and then searching from there. Snowpack (😅) and Vite both have their own version of this: https://github.com/FredKSchott/snowpack/blob/7f9b5455683a9d7632dbd7f4ed6db9ec2bb7c760/skypack/src/util.ts#L79-L126

Vite may have exposed this as a helper by now, or maybe exists as an npm package, I'm not sure. but naive `fs.read` approach will break.

Comment (southpolesteve) [reply packages/vinext/src/init.ts:155]: Good call — addressed in 45fabe9.

Both `getReactUpgradeDeps` (init.ts) and `getMissingDeps` (deploy.ts) now use `createRequire` instead of reading `node_modules` directly:

- **init.ts**: `createRequire(root/package.json).resolve("react")` → `findPackageVersion()` walk-up to get the version from `package.json` (same pattern as `findReactServerPackages` in PR #18)
- **deploy.ts**: new `isPackageResolvable()` helper wraps `createRequire().resolve()` for the rsdw check

This handles hoisting, pnpm symlinks, monorepos, and Yarn PnP correctly. The one gotcha: Vitest intercepts `createRequire` and resolves from the project root even for tmpdir-based tests, so the deploy test uses dependency injection for the resolver function instead of filesystem isolation.
